name: deploy backup workflow

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  deploy-backup-workflow:
    runs-on: self-hosted
    env:
      GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      IHTM_METADATA_BASE_ID: ${{ secrets.IHTM_METADATA_BASE_ID }}
    steps:
      - uses: actions/checkout@v6
          
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Run workflow
        run: |
          targets::tar_make()
        shell: Rscript {0}

      - name: Move backup
        run: |
          rsync -av --progress data/. ~/Documents/ihtm-backups/airtable

